version: "3.5"
services:
        ssh:
                image: ssh-tunnel-client
                build: ./build/
                environment:
                        - "REMOTE_HOST=192.168.11.21"
                        - "REMOTE_PORT=10122"
                        - "REMOTE_LISTEN=80"
                        - "LOCAL_HOST=localhost"
                        - "LOCAL_PORT=9000"

